### ISSUE TITLE
We need some room to breathe!

### ISSUE THREAD

**Issue by THEjoezack** [codingblocks/podcast-app#133] opened 2018-06-22 23:17 UTC
![image](https://user-images.githubusercontent.com/81006/41802720-dfcada60-7650-11e8-8d02-cbf88afad589.png)

Firro knows!

**Comment by dance2die** [comment] 2018-06-23 01:54
Reproduction steps?
What browser, and how did that occur?

**Comment by MinimumViablePerson** [comment] 2018-06-23 13:31
This is a very old version of the app, I had actually fixed this issue about 2 weeks ago now. The problem was Windows showing those nasty scroll bars when content was scrollable, but this is no longer the case. Closing!

**Closed** 2018-06-23 13:31 UTC
Labels: enhancement
